desc "Build debug binaries"

task :build do
    sh "dotnet restore && dotnet build"
end

desc "Clean project directory"

task :clean do
    sh "dotnet clean"

end

desc "Install release"

task :install do
    sh "mkdir -p /opt/EchoSeven"
    sh "dotnet publish -c Release -o /opt/EchoSeven"
    sh "cp ./EchoSeven.service /etc/systemd/system/EchoSeven.service"
    sh "useradd -r -s /sbin/nologin echoseven"
    sh "systemctl daemon-reload"
end

desc "Remove release"

task :remove do
    sh "systemctl stop EchoSeven"
    rm_r FileList["/opt/EchoSeven*"]
    rm FileList["/etc/systemd/system/EchoSeven.service"]
    sh "userdel echoseven"
    sh "systemctl daemon-reload"
end